### ISSUE TITLE
Impossible login on Google account

### ISSUE THREAD

**Issue by LlamasJM** [ubports/ubuntu-touch#1135]
### Description of the feature
On "Accounts", I try to add my Google account. The finale message is: "Session start (Login) temporary disabled with Google on this application". But Google send me a message: "You have begun session with Google on an unknown device".
And after that, this message: "We haven't verified still this application to use Google session login". In Spanish: "Todavía no hemos verificado esta aplicación para que pueda usar el inicio de sesión de Google". Same with two different Google accounts.
I have "less secure apps access" with Google.

### Illustrations

- Device: Frieza
- Channel: Stable
- Build: Ubuntu 16.04 (OTA 9).

**Comment by mardy** [comment]
I just tried, and I cannot reproduce the error. @LlamasJM, could you please add some screenshots? Especially I'd like to see the first screen where you see an error message. Is it after or before entering your username and password?

Is anyone else able to reproduce this bug as well?

**Comment by LlamasJM** [comment]
After entering my username and password. Here, some screenshots.
![screenshot20190511_002043207](https://user-images.githubusercontent.com/35621579/57559598-fa12f580-7382-11e9-8647-ae636390826d.png)
![screenshot20190511_002049400](https://user-images.githubusercontent.com/35621579/57559600-fc754f80-7382-11e9-9468-30b8b599b4b5.png)

**Comment by cibersheep** [comment]
It seems to work on the latest updates on E5 and N5 but not on M10

**Comment by UniversalSuperBox** [comment]
Now that we've got new keys in place, can you try again? The full release of these will be with OTA-10, but the image in `devel` right now (and the next RC image, 2019-W31 and newer) will have them.

**Comment by cibersheep** [comment]
On m10hd (dev channel), now I can «permit access», the add account window closes but the account is not in the list

**Comment by mardy** [comment]
Would you be able to produce a short video of this? Or do I understand correctly, that everything appears to work fine, except that the account is not created?

**Comment by cibersheep** [comment]
@mardy I could record a video if you like but yes, it's like you say: all is working correctly except that the account is not created into Accounts.

**Comment by mardy** [comment]
Hi @cibersheep, could you please follow the steps [here](https://ci.ubports.com/job/docs.ubports.com/job/PR-240/1/artifact/_build/html/systemdev/online-accounts.html#account-creation-issues) to get debugging information out of the Online Accounts service?

**Comment by cibersheep** [comment]
Sure. I'll do tomorrow (my tomorrow :D)

**Comment by cibersheep** [comment]
@mardy https://paste.ubuntu.com/p/BTfbJ5jM5W/
Tell me if you need more things

**Comment by mardy** [comment]
That's interesting, thanks @cibersheep! Indeed, it looks like something is crashing (not sure whether it's the browser or the online-accounts-ui process). However, this looks like a different bug than the one originally reported, and my impression is that the bug you found should potentially affect all accounts using the webview, not just Google. Can you try to see if you get the same problem with Twitter or Facebook?

**Comment by cibersheep** [comment]
Mmmm...interesting.
I don't have the possibility to add facebook or twitter accounts (Canonical apps have been uninstalled?) but I did with Evernote, I have cancelled the process a couple of times and Unity8 crasehd the first time I tried to add an account. Second time was ok, account added

https://paste.ubuntu.com/p/Y6NpbHsWWZ/

**Comment by cibersheep** [comment]
Adding a Google account:
 - After the «Authorize UBports» page, I receive an email saying I have added my Google account
 - qml page shown afterwards is «Add an account» (when added Evernote account succesfully, the qml page shown is «Accounts»)
 - No Google account is added

**Comment by cibersheep** [comment]
Just for the record: adding a Google account on E5 works well.
Do you wsnt me to open a separated issue for the tablet?

**Comment by dekkerj1** [comment]
I have the same problem on BQ M10

**Comment by LlamasJM** [comment]
I think it's an issue (OTA 10 did not solve it) at least on the tablet BQ Aquaris M10, «Cooler» and «Frieza»...

**Comment by dekkerj1** [comment]
I have opened issue #1202 for the tablet BQ M10.

**Comment by nathangiovannini3** [comment]
I confirm that this issue also remains on Build in the Edge channel. Build 2019-09-05/2

**Comment by cibersheep** [comment]
Update: on M10HD OTA10 we got again «Google login disabled for this application».
Still works great on E5HD

![imatge](https://user-images.githubusercontent.com/6640041/64386890-9cde3680-d03a-11e9-8bd8-97d19c43d2e8.png)

**Comment by UniversalSuperBox** [comment]
I can confirm this as well. It seems that we get sent to a different login screen for SSO to a website rather than an app... it says "sign in to continue to ubuntu.com". Unfortunately I don't have a screenshot right now.

**Comment by YougoCodes** [comment]
Confirmed on Bq M10 on Edge as well as Devel, and on FP2 on devel

**Comment by UniversalSuperBox** [comment]
![screenshot20190908_121052734](https://user-images.githubusercontent.com/21966173/64491774-c614e780-d231-11e9-90e9-b79f90d20812.png)

This is an example of the incorrect login. Have you ever seen this before @mardy? It seems to happen more on edge than anywhere else.

**Comment by YougoCodes** [comment]
![5F22AD99-A309-46DD-9585-FCF46CD525DA](https://user-images.githubusercontent.com/23282697/64491840-1a898880-d26d-11e9-8bb3-d096b5ca56b7.jpeg)
If you click on the “Ubuntu.com” this pops up.

**Comment by mardy** [comment]
No, I didn't see this before :-) I wonder if the commit which was reverted [here](https://github.com/ubports/account-plugins/commit/f7f1d1472f6951953a0814e5b4d49d8908edc386) can help?

(though I doubt that it will have any effects on the zoom level)

**Comment by UniversalSuperBox** [comment]
I've just managed to sign in on the devel channel without issue. I wonder if the issue was a package stuck behind on edge...

**Comment by cibersheep** [comment]
I still have the same message (Login for this app has bee disabled) on Cooler.

**Comment by UniversalSuperBox** [comment]
I believe this issue duplicated https://github.com/ubports/ubuntu-touch/issues/1202, and both should now be fixed.

**Comment by cibersheep** [comment]
Confirmed with the last dev... weeee!

**Comment by Flohack74** [comment]
Oh wow need to test immediately...

**Comment by Flohack74** [comment]
I still get this after update:
![grafik](https://user-images.githubusercontent.com/16186470/72988739-22e1fa80-3ded-11ea-9a43-6a3f64f6b3a5.png)
