### ISSUE TITLE
Input method properties aren't always updating in QtWebEngine text fields.

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-touch#1157]
- Device: Nexus 5, Nexus7 2013, Meizu MX4
- Channel: All

### Steps to reproduce
1. Open a site with a text field in the Morph browser.
2. Focus on a text field.
3. Type any texts.
4. Press and hold the space bar.
5. Try to move the cursor to left and right.

### Expected behavior
The text cursor moves left and right without problems.

### Actual behavior
The text moves to the left but not to the right.

### Logfiles and additional information
This issue happens because `input_method.surroundingLeft` and `input_method.surroundingRight` does not update correctly. These are being checked when moving the cursor and if they are blank, the cursor won't move to avoid horizontal cursor movement go to the next or previous line.

This can also be true to other properties of `maliit_input_method` such as `hasSelection`.

**Comment by kugiigi** [comment]
The same issue happens on the Terminal app.

**Comment by mauricioduarte01** [comment]
Happens to me too. N5, devel.

**Comment by TartanSpartan** [comment]
Confirmed on arale and turbo.

**Comment by UniversalSuperBox** [comment]
Has this been fixed in a recent update? It seems like I can move the cursor using the spacebar now.

**Comment by kugiigi** [comment]
Haven't checked again but it works now because I've removed the conditions that checks the surrounding texts before moving the cursor.

**Comment by kugiigi** [comment]
I've tried this again and it does seem to work properly on `QtWebEngine` now. At least `surroundingLeft`, `surroundingRight` and `hasSelection` since those are the things that are currently used in the cursor mover mode.
Detection of surrounding text seems to behave a bit different than UITK though because when I enabled the code to prevent moving the cursor to the next line, it still happens in `QtWebEngine`. Also, sometimes it seems that there's a bit of a delay getting the values of these properties so the cursor can't be moved for a moment.

**Comment by UniversalSuperBox** [comment]
I have a very strong feeling that the delay in updating the properties is going to be related to https://bugreports.qt.io/browse/QTBUG-91257. I don't know for a fact... but I'm pretty sure.

So what should we do with this report? Leave it open? Open new, more specific reports?

**Comment by kugiigi** [comment]
I did more tests on this and here are my findings.
- The issue still exists in the terminal app. Surrounding text properties are not updated and are always blank.
- There are indeed a delay in the surrounding texts in `QtWebbEngine` but it's rare and barely noticeable.
- The issue of not moving wasn't because of the delay I mentioned, it's because surrounding texts are blank on initial focus to a text field in `QtWebEngine`. They are only updated once the cursor position changed. After that, they seem to work fine.
- `hasSelection` seems to work fine now although not sure if it also doesn't update on initial focus since focusing will remove the text selection.

I think it's better to close this and open separate more specific issues -  one for terminal and one for QTWebEngine.

**Comment by kugiigi** [comment]
Closing this since this is partially fixed now. More specific issues have been logged for the remaining issues.
