### ISSUE TITLE
Wifi doesn't works in OP3t

### ISSUE THREAD

**Issue by testingweb624** [ubports/ubuntu-touch#1356]
After reboot Wifi works flawless when i switch wifi to off and back to "on" the wifi stops working in OP3T

Because of this wifi problem, sometimes hotspot doesn't turns on. Keeps saying "turn on wifi" whereas I switched wifi to "on" and not working.

**Comment by ernesst** [comment]
@Flohack74 Similar to https://github.com/ubports/ubuntu-touch/issues/1296

See my quick fix... works well.

**Comment by andybleaden** [comment]
I test this today and can not reproduce the error any more

I can switch off the wifi and turn back on again and it functions 

I can also confirm that the issue of switching on the aeroplane mode and then switching off again no longer breaks Wifi so can this marked as resolved?

**Comment by testingweb624** [comment]
Installing update at the moment will report now. Asap

**Comment by testingweb624** [comment]
Yes it's resolved now.

Great job. ;)

**Comment by ernesst** [comment]
for reference fixed by https://github.com/Halium/android_device_oneplus_oneplus3/pull/12

**Comment by Flohack74** [comment]
How can WiFi fix also fix Bluetooth? And how does this correlate to #1330 ??

**Comment by ernesst** [comment]
It does not fix or correlate with BT

On Wed, 26 Feb 2020 10:03:04 -0800, Florian Leeber wrote:
> How can WiFi fix also fix Bluetooth? And how does this correlate to #1330 ??
>

--

**Comment by ernesst** [comment]
For reference : https://github.com/Halium/android_device_oneplus_oneplus3/pull/18
The device name was changing after reloading the driver thus confusing network-manager.

**Comment by userj** [comment]
Sometimes wifi can detect the networks, but it won't connect to them. Requires a reboot.

**Comment by ernesst** [comment]
Yes one the commit land it should be fine.

**Comment by Flohack74** [comment]
So I can close it?
