### ISSUE TITLE
reopen #1245 lower part of launcher not accessible when OSK is raised

### ISSUE THREAD

**Issue by Danfro** [ubports/ubuntu-touch#1370]
This issue is to reopen #1245 because it is still valid. This issue was not fixed with [ubports/unity8#206](https://github.com/ubports/unity8/pull/206). While I can not reopen the original issue, I create a new one, so we don't miss this out.

Device: E5
Channel: devel
Build: 2020-02-14

Steps to reprocuce:

- open launcher
- type something in search bar to raise the OSK
- swipe the launcher towards the icons in the lower part of the launcher

Expected behaviour:

- all icons can be reached

Current behaviour:

- the lower icons are hidden behind the OSK, the launcher can not be scrolled low enough to reach them

Possible solutions:
- When the launcher is moved OR when the search bar looses the focus the OSK is dismissed
- The launcher is resized so its bottom matches top of OSK

**Comment by thilovv** [comment]
Works fine now!

**Comment by cibersheep** [comment]
N5, M10HD on RC: issue is fixed

**Comment by Danfro** [comment]
Fix confirmed on suzu, devel

Fix not confirmed on E5 RC 2020-W13. @cibersheep  you are sure your devices are RC? :thinking:

**Comment by thilovv** [comment]
@Danfro works on mine BQ E5 rc (2020-W13)

**Comment by abkro** [comment]
Works on my N5 and my BQ E4.5

**Comment by Danfro** [comment]
Hm. Just rebooted my E5. Still not working. But looks like my device is the bad boy around here. ;-)
