### ISSUE TITLE
First time granting access to microphone, breaks microphone for all other apps too (qt 5.12 issue?)

### ISSUE THREAD

**Issue by luksus42** [ubports/ubuntu-touch#1668]
Devices: Nexus 5, Fairphone 3, BQ e4.5
Channel: dev

I assume this happens since QT 5.12 update.
If your html5-app or Morph-Browser for example, already did have permission to use the microphone or are in the permissions-list displayed at least, then everything works as expected.

### Expected Behavior
- Opening html5 app / open any microphone recording page in Morph 
- website asks for permission
- when choosing "yes", system asks for permission if it is not already in the systems allowed apps.

### Current Behavior
- Starting html5 recording test app / opening any microphone recording page in Morph
- website asks for permission
  - when choosing "yes": 
    - system does not ask for permission, the app is not saved in the permissions-list for the microphone
    - No other App can use the microphone until a lomiri restart (recorder App for example)
  - when choosing "no":
    - the app is not saved in the permissions-list for the microphone
    - microphone is still usable by other apps

Here is a test html5 app:
[html5rectest.zip](https://github.com/ubports/morph-browser/files/5954267/html5rectest.zip)

related: https://github.com/luksus42/soundrecog/issues/6
maybe related: ubports/morph-browser#455 , ubports/morph-browser#399

**Comment by luksus42** [comment]
Thanks for the quick look into it.

Are there already some changes in dev?
I just discovered, that my test-app is now displayed in the app-microphone-permissions-site in system settings. So I could grant the access to the app and now it is working.

**Comment by peat-psuwit** [comment]
Merged ubports/trust-store#14 allows other apps to request microphone after Morph Browser fails to, but doesn't fix the issue with the Morph Browser itself.

**Comment by Flaburgan** [comment]
> Merged [ubports/trust-store#14](https://github.com/ubports/trust-store/pull/14) allows other apps to request microphone after Morph Browser fails to, but doesn't fix the issue with the Morph Browser itself.

When trying with jitsi meet for example on https:/framatalk.org/morph-test there is progress though: before I wasn't able to actually join the room, the screen being stuck on "Please allow access to your microphone" even after saying yes to the prompt. Now when I say yes I reach the room but jitsi still complains it can't reach my mic.

**Comment by UniversalSuperBox** [comment]
Since the issue with Morph blocking access to the microphone for all other apps has been solved and the issue with Morph being unable to access the microphone is filed as https://github.com/ubports/morph-browser/issues/399, I will close this report.

For QA: The issue went as follows:

1. Start with morph-browser not having asked for microphone input (for example, a newly reset device)
2. Attempt to use the microphone with morph-browser
3. Note that the trust-store request for microphone access never appears and the webapp's request never completed (it would still say "waiting for microphone access" usually)
4. Open another app which has never used the microphone before, and get it to bring up its request (for example, open the Recorder app and try to record a voice message)

The prompt for the Recorder app would never appear. A reboot was required to give access to Recorder.

Now, the webapp's request for microphone access will complete with a denial, and it will be possible to grant access to the other app.

**Comment by dadandalive** [comment]
I confirm that after a fruitless attempt of Morph to get access to the microphone (went to voicechanger.io, replied affirmative to browser's request for domain access to microphone, still saw 'please enable microphone' button without receiving a secondary system permission request, and kept the page open as such), other apps still can be granted access to the microphone (tried with freshly installed 'guitar tools' app).

I didn't manage to reset my device settings to standard values (~ reset request freezed settings app, without resetting any settings), but in any case Morph wasn't listed among the apps with microphone access (in system's privacy settings) nor was any domain already listed (in Morph's own privacy settings) as having access to the microphone.

**Comment by Flohack74** [comment]
@dadandalive this should finally be fixed, plz give it a try...

**Comment by Flaburgan** [comment]
Using today's development build on the pinephone, it looks like https://framatalk.org/test still isn't able to access my microphone.

**Comment by peat-psuwit** [comment]
Huh, have the trust-store prompt ever worked on Pinephone, given that it uses Wayland for the whole stack? Can other applications request microphone on Pinephone?

**Comment by Flaburgan** [comment]
The trust prompt is here, it asks me to grant access to the camera and then to the microphone, I do, and then the website says that an unknown error blocked them to access the mic.

**Comment by Flaburgan** [comment]
I had the same behavior with my FP2 when it was running UT. It is now running /e/ OS so I can't test anymore sorry.

**Comment by ivoxavier** [comment]
Hi, 

I've tested on the FP2 with the click app provided in the description and after granting access to microphone it did not broke the apps that I've previously, and still able to record voice messages on TELEports and Recorder App.

Tested was performed on Devel channel: image from (2021-11-12).

**Comment by UniversalSuperBox** [comment]
The PinePhone has never worked with trust-store, and instead allows all requests to microphone.

**Comment by luksus42** [comment]
This specific issue is solved.
Other errors like not appearing trust-prompts or errors on mic-recording in browser or webview should be handled in separete issues.
