### ISSUE TITLE
[xenial] Bluetooth headset stops sending and receiving call sounds after a second from the call starts

### ISSUE THREAD

**Issue by freezeloud** [ubports/ubuntu-touch#830]
- Device: Krilin
- Channel: RC
- Build: 2018-W33

### Steps to reproduce
- Have bluetooth headset connected to the phone. (I am using Sennheiser HD 4.40BT)
- Start a call. You will hear ringing in the headphones.

### Expected behavior
Being able to use BT headset as usual.

### Actual behavior
- After a second or two it will became silent - no more ringing or call sounds.
- The call is ok, other end cannot hear anything though and you neither.
- When switching to phone audio through call app you can use your phone normally - without the BT headset, to finish the call.

### Logfiles and additional information
[UTlogcat_bluetooth.txt](https://github.com/ubports/ubuntu-touch/files/2311278/UTlogcat_bluetooth.txt)
[UTdmesg_bluetooth_and_call_ui_crashing.txt](https://github.com/ubports/ubuntu-touch/files/2311279/UTdmesg_bluetooth_and_call_ui_crashing.txt)
I have been reporting other issue of crashing Phone app when receiving a phone call. So the logs might contain also those errors. Sorry, I don't know how to clear them or what to look for in them.

**Comment by Wend1go** [comment]
- Device: FP2
 - Channel: RC
 - Build: 2018-W40

I encounter the same behaviour when trying to make a phone call via the Honda Jazz hands-free car kit.
The phone pairs just fine and I can navigate through the contacts but upon starting a call it reproducibly beeps just one time (the phone on the other end also rings once) and then terminates.
After trying for the third time the phone suddenly rebooted.
This used to work perfectly in Vivid.

If someone would be so kind to tell me where I can find the logs I will upload them here.

**Comment by corvusd** [comment]
Same for me. In me case Toyota touch system. With 15.04 work OK. Music work OK

**Comment by mariogrip** [comment]
I have pushed the latest version (5.50) of bluez to xenial_-_new-bluez please try this to see if it fixes the issue :)

`sudo ubports-qa install xenial_-_new-bluez`

**Comment by tomoqv** [comment]
My Pro5 gets stuck on `Configuring bluez (5.50-0ubuntu3) ...`

**Comment by tomoqv** [comment]
Some further info. Issuing the above command again yields the following (sorry for the Swedish lang):
```
Bra:1 http://ports.ubuntu.com/ubuntu-ports xenial InRelease
Läs:2 http://ports.ubuntu.com/ubuntu-ports xenial-updates InRelease [109 kB]
Ign:3 http://repo.ubports.com xenial_-_new-bluez InRelease
Ign:4 http://repo.ubports.com xenial InRelease                                 
Bra:5 http://repo.ubports.com xenial_-_new-bluez Release                       
Läs:6 http://ports.ubuntu.com/ubuntu-ports xenial-security InRelease [109 kB]
Läs:7 http://repo.ubports.com xenial Release [6 309 B]                         
Läs:8 http://repo.ubports.com xenial Release.gpg [473 B]                       
Läs:10 http://repo.ubports.com xenial/main armhf Packages [1 478 kB]
Hämtade 1 703 kB på 3s (446 kB/s)
Läser paketlistor… Färdig
Bygger beroendeträd       
Läser tillståndsinformation… Färdig
1 paket kan uppgraderas. Kör ”apt list --upgradable” för att se det.
W: No sandbox user '_apt' on the system, can not drop privileges
Läser paketlistor… Färdig
Bygger beroendeträd       
Läser tillståndsinformation… Färdig
Beräknar uppgradering… Färdig
Följande paket kommer att uppgraderas:
  messaging-app
1 att uppgradera, 0 att nyinstallera, 0 att ta bort och 0 att inte uppgradera.
1 är inte helt installerade eller borttagna.
Behöver hämta 529 kB arkiv.
Efter denna åtgärd kommer ytterligare 0 B utrymme användas på disken.
Vill du fortsätta? [J/n] 
Läs:1 http://repo.ubports.com xenial/main armhf messaging-app armhf 0.1.3~0ubports0+0~20190512054900.26~1.gbp13032a [529 kB]
Hämtade 529 kB på 0s (1 193 kB/s) 
(Läser databasen ... 50971 filer och kataloger installerade.)
Förbereder att packa upp .../messaging-app_0.1.3~0ubports0+0~20190512054900.26~1.gbp13032a_armhf.deb ...
Packar upp messaging-app (0.1.3~0ubports0+0~20190512054900.26~1.gbp13032a) över (0.1.3~0ubports0+0~20190504045128.25~1.gbpd2d4cd) ...
Hanterar utlösare för mime-support (3.59ubuntu1) ...
Ställer in bluez (5.50-0ubuntu3) ...

Förlopp: [ 33%] [####################......................................] 

```
Checking bluez version gives this:
```
phablet@ubuntu-phablet:~$ bluetoothd -v
5.50

```

**Comment by m0n5t3r** [comment]
in my case (Nexus 5) it is really loud for 1-2s, then goes silent

**Comment by m0n5t3r** [comment]
> Ställer in bluez (5.50-0ubuntu3) ...
> 
> Förlopp: [ 33%] [####################......................................] 
> ```
> 
> But it never finishes the above, stays on 33%...

had this happen to me, turns out `stop bluetooth` / `start bluetooth` were hanging; I killed the stop and then start  processes from another console, then everything else installed correctly; after a reboot and running `dpkg --configure -a` the `stop bluetooth` part worked, `start bluetooth` was still hanging

eventually I commented out the restart line in the postinst script so everything else could proceed, but bluetoothd still won't start
