### ISSUE TITLE
Unity 8 crashes when shutdown button is pressed (Krillin)

### ISSUE THREAD

**Issue by Rom4nB** [ubports/ubuntu-touch#85]
**What happened:** Unity 8 crashes when many apps are opened.

**What I expected to happen:** The phone should shut down.
    Steps to reproduce: Start many apps like camera, Telegram, browser and music. Press the On/Off button and select "Shutdown" or select "Shutdown" in the "System" tab of the top Unity 8 menu bar. Unity 8 will crash. The orange Ubuntu Touch background and the UBPorts splash screen is seen and Unity 8 restarts. After restart from Unity 8 and pressing the shutdown button again, the shutdown works now.

**Software Version:** Ubuntu 15.04 (r5) (Legacy Channel stable)

**Comment by Flohack74** [comment]
Please can you attach the log as a file, not paste it into this box? Simply drag/drop it from the file manager. Second thing is: This looks like a logcat log? This is not so useful to us. We need logs from /var/log, which I cannot say not for unity8...

**Comment by doniks** [comment]
Maybe the logs you care for are actually in ~/.cache/upstart probably best to check for files with latest changes ls -ltr

**Comment by Rom4nB** [comment]
Hi Flohack74, hi doniks.

thanks for your answer. I changed the log files above.

It happened again. I noticed it doesn't happen at all shutdown attempts but at about 30% of the attempts altogether. 2nd attempt after Unity 8 crash always works, same the shutdown with terminal command.

I just copied /var/log (as far was possible with non-root privilegdes) to my laptop after the Unity 8 crash.

The ~/.cache/upstart has some files that were changed recently, the screen after ls -ltr:
![bildschirmfoto vom 2017-06-07 23-34-30](https://user-images.githubusercontent.com/19626851/26902699-8cefeca0-4bda-11e7-94d3-1715faf55b93.png)

I think the two unity 8 logs are maybe the most interesting. I added the last part of it also as attachment. 
[unity8.log.txt](https://github.com/ubports/ubports-touch/files/1059426/unity8.log.txt)
[unity8-dash.log.txt](https://github.com/ubports/ubports-touch/files/1059425/unity8-dash.log.txt)

I found these lines in unity8-dash.log maybe interesting:

> [2017-06-07:23:22:21.643] ubuntumirclient: Attempted to deliver an event to a non-existent window, ignoring.
[2017-06-07:23:22:22.899] "There are still "4" items in the process of being created at engine destruction."
Attempted to unregister path (path[0] = com path[1] = canonical) which isn't registered
Attempted to unregister path (path[0] = com path[1] = ubuntu) which isn't registered
Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'
[2017-06-07:23:22:23.866] UbuntuClientIntegration: connection to Mir server failed. Check that a Mir server is
running, and the correct socket is being used and is accessible. The shell may have
rejected the incoming connection, so check its log file
Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'
[2017-06-07:23:22:24.356] UbuntuClientIntegration: connection to Mir server failed. Check that a Mir server is
running, and the correct socket is being used and is accessible. The shell may have
rejected the incoming connection, so check its log file
Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'
[2017-06-07:23:22:24.636] UbuntuClientIntegration: connection to Mir server failed. Check that a Mir server is
running, and the correct socket is being used and is accessible. The shell may have
rejected the incoming connection, so check its log file
Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'
Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'
[2017-06-07:23:22:43.072] Requesting initial location update

**Comment by Rom4nB** [comment]
Hello guys,
did anyone watch the log files related to this bug? Did they help?
The issue is still present on my phone in about 30% of the shutdown events ...

**Comment by Flohack74** [comment]
Just an assumption: If you got many Apps opened you will be on virtually no memory left. Any further task that can consume memory (like starting the shutdown-sequence by displaying an overlay window) could lead to unity being kicked out of memory and restarting. Can you try to close all Apps before you restart? Does it then happen also? 1GB RAM is not enough for UBports and thats a hjuge flaw on the BQ E series...

**Comment by Rom4nB** [comment]
Well I tried also shutting down all Apps and still sometimes it crashes. As I said, I didn't find a way to 100% reproduce it. It seems that many apps open/lot of RAM used increases the probability of a crash. 

Maybe it is also a device specific problem as I haven't heard from other BQ users to have a similar problem ...

**Comment by NeoTheThird** [comment]
So, nobody could reproduce this so far? @Rom4nB Are you still experiencing this issue?

**Comment by Rom4nB** [comment]
@NeoTheThird Yes, I still experience it. However, frequency of unity 8 crash seems to be reduced, since I follow Flohack's advice, to close al applications manually before shutdown.

**Comment by Rom4nB** [comment]
@NeoTheThird @Flohack74 
I checked now for several days. When I consequently close all apps before shutting down, Unity 8 does not crash and shutdown works normally. I.e. it is a general problem of the limited RAM in the BQ Aquaris E4.5 device and doesn't seem to be a bad functionality of the UBPorts Image.

Maybe you could consider to try include a workaround in a future OTA anyway: e.g. that the shutdown sequence first closes all processes with pkill or something (I dunno if this is possible or would help), but I'd say the problem is understood now.

**Comment by NeoTheThird** [comment]
@Rom4nB Ok, thank you for the confirmation. That shouldn't be too difficult to fix.

**Comment by Rom4nB** [comment]
Ok. Thank you @NeoTheThird

**Comment by Gabriele69** [comment]
hi, I tried to reproduce it in my BQ E4.5. but nothing appened.
I no longer have Ubuntu 15.04 (r5) (Legacy Channel stable) but the UBports version 14.04 r1. It could be something fixed in the transition to Ubports.

**Comment by Flohack74** [comment]
@Rom4nB Is this still an issue for you?

**Comment by abkro** [comment]
I tried to reproduce this issue, but for me things worked fine on krillin with Xenial r89. I had 6-7 apps open. Maybe too few?

**Comment by abkro** [comment]
I tested this today running r90 on krillin. I'm leaving out my very first attempt because I wasn't attentive enough, so I am not 100% sure what I observed. The subsequent tests done and results were as follows.

First I tried to reproduce the issue by opening 8 different apps each time and then pressing/holding the power button. Three attempts went as follows: Each time, the dialogue to power off/reboot appeared after about 2 seconds. I waited an additional 8 seconds approximately before anything else happened. This was consistent. After about 10 seconds (total) this is what the three attempts gave:

1. Screen went black. bq splash appeared. Device rebooted.
2. Device powered off.
3. Same as first attempt above.

I then tried the same without unlocking the screen at all, i.e. I had the opening lockscreen and pressed and held the power button from there. I tried this four times. Results:

1. No dialogue to power off/reboot. Rebooted with bq splash first after about 10 seconds.
2. Dialogute to power off/reboot after 2 seconds. Rebooted with bq splash after a total of about 10 seconds.
3. Dialogue to power off/reboot. Powered off completely.
4. No dialogue to power off/reboot. Same as first attempt above.

Attempts 1 and 4 had the following in common. I started pressing the power button just after the lock screen had appeared. In attempts 2 and 3 I waited a few seconds before doing this.

**Comment by Rom4nB** [comment]
I just want to remark, that I still face this bug with Unity 8 crashs when I want to shut down the phone with my new Fairphone 2, stable channel, OTA-6.
The crash does not happen always, but when it happens usually the second attempt to shut down the phone, after Unity 8 restarted, works fine.

Is there somebody else with this experience?

**Comment by Flohack74** [comment]
Again asking whats the situation here, did it improve? :)

**Comment by abkro** [comment]
Sorry for not having seen your question. I am not experiencing this issue any more. Now running RC (2020-W13) updated 5 days ago.

**Comment by Rom4nB** [comment]
Dear Flohack74, I flashed now UT (OTA 12, stable channel) again on my FP2 and I still have this issue.

When I slide down the top menu -> System -> Shut down -> Button "Switch off" still in like 30% of the cases all works normal: the screen goes black, phone switches off.

In like 70% of the cases, Lomiri crashes and restarts, when I select the Button "Switch off". After Lomiri restart, I'm in the phone lock screen. When I then slide down the top menu and select everything to shut down the phone, in the second attempt it always works. 

Honestly, I don't remember always to first close all apps before selecting shut down, so it could be this RAM issue. Was the shutdown routine changed in the meantime that first all running applications are killed and then the shutdown procedure is started?

**Comment by Flohack74** [comment]
No, nothing was changed in this area. But ultimately a shutdown will kill all processes, but its not really predictable how it happens. Honestly I have no idea what to do here... You might want to wait fore the new Halium-7.1 based port, that might make things a bit more stable.
