### ISSUE TITLE
[xenial] Implement Halium in Ubuntu Touch

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubuntu-touch#89]
[Halium](https://halium.org/) promises to unify our Android hardware compatibility layer with other GNU/Linux distributions. It provides a port-once, run-anything interface, so one developer's successful Halium port will open a device up to Ubuntu Touch, Plasma Mobile, and any other distributions that choose to use it.

In order to consider a 16.04 image for release, Halium will need to be fully implemented in Ubuntu Touch. This includes:

* Ensuring that Halium upstream is in a stable state
* Packaging Halium for Ubuntu
* Any other Ubuntu-specific implementation details

**Comment by doniks** [comment]
Fix Released!? For real? Nice (assuming I understood this right :) ). Where's the press release or something? I mean this is big news and it is being promoted, right?

**Comment by WLBI** [comment]
@doniks @NeoTheThird 
I also assuming Halium should be released when closing this thread. I wonder too...

**Comment by Flohack74** [comment]
Current issues with Halium and our core devices:
* N5 https://github.com/Halium/projectmanagement/issues/8
* FP2 https://github.com/Halium/projectmanagement/issues/10
* OPO (no tracker yet)
* M10 HD (no tracker yet)
* M10 FHD (no tracker yet)

As long as these problems are not solved, Halium cannot be considered stable enough for UBports. So, this ticket must be re-opened.

**Comment by Flohack74** [comment]
Due to the possibility to boot with upstart instead with systemd I don't see this as a blocker anymore. Opinions?

**Comment by UniversalSuperBox** [comment]
I feel that #404 is possibly a duplicate of this now. Would you agree, @Flohack74?
