### ISSUE TITLE
Calling a contact from Messaging app

### ISSUE THREAD

**Issue by james-lyon** [ubports/ubuntu-touch#968]
### Illustrations

   - Device: BQ E4.5
  -  Ubuntu 16.04 (OTA-5)

### Steps to reproduce
- Open Messaging app
- Open conversation with a contact
- Tap "telephone" icon in top right corner

### Expected behavior
I would expect the Phone app to open with the contact's phone number ready to call

### Actual behavior
The Phone app opens but the number field is blank. I have to go into the address book to select the phone number.

**Comment by UniversalSuperBox** [comment]
I'm not able to confirm this on my Nexus 5 or Fairphone 2 running devel 2018-11-26/2. It's possible that the issue has been fixed since the release of OTA-5.

**Comment by tydell** [comment]
On N5 dev channel it works as expected.

**Comment by Gabriele69** [comment]
On my BQ E4.5 RC channel it works as expected. 
I think the error is due to how the information is stored in your contact card. Try creating a fictitious contact with NAME, SURNAME and a single phone number. Then look what happens.
Gabriele

**Comment by james-lyon** [comment]
@Gabriele69 it doesn't seem to make any difference how the information is stored in my contacts. It looks like the issue will be fixed on an upcoming release - I'm not running a dev release.

**Comment by james-lyon** [comment]
I am now running OTA-7 and the issue still hasn't been corrected. Behaviour is exactly the same as in my original post.

**Comment by Gabriele69** [comment]
> I am now running OTA-7 and the issue still hasn't been corrected. Behaviour is exactly the same as in my original post.

Are your contacts originally on the SIM or phone?

**Comment by james-lyon** [comment]
I have contacts on the SIM and on the phone (synchronised to a google account) and I have the same behaviour for both types of contact.

**Comment by Gabriele69** [comment]
I can't help you. No problems in my phone. Can you reinstall the system?

**Comment by UniversalSuperBox** [comment]
I'm also not able to reproduce this at all... I'll see if I can find another person with an E4.5 and bring them in here.

**Comment by MatthiasPaul** [comment]
I have a E4.5 Ubuntu Edition running on 16.04 (OTA-7). When I follow the above steps the phone app opens with the telephone number of the contact ready to call. So it is the expected behaviour.

**Comment by james-lyon** [comment]
> I have a E4.5 Ubuntu Edition running on 16.04 (OTA-7). When I follow the above steps the phone app opens with the telephone number of the contact ready to call. So it is the expected behaviour.

@MatthiasPaul , are you using two SIMs on the E4.5?

**Comment by kwah-gh** [comment]
Also cannot reproduce. E4.5 16.04 rc (2018-W01) should be 2019-W01, I recon.

I do use two SIMs.

The only issue I've noticed is that even when SMS is received on SIM2, dialer pops up with SIM1 selected. This is the same behavior (bug?) as for received calls.

**Comment by Gabriele69** [comment]
> Also cannot reproduce. E4.5 16.04 rc (2018-W01) should be 2019-W01, I recon.
> 
> I do use two SIMs.
> 
> The only issue I've noticed is that even when SMS is received on SIM2, dialer pops up with SIM1 selected. This is the same behavior (bug?) as for received calls.

This probably stems from the fact that you set SIM 1 as the default SIM for both messages and calls.

**Comment by james-lyon** [comment]
Okay, I'll try and do a backup and completely reinstall the system. Maybe this will fix my other possibly related issue: https://github.com/ubports/ubuntu-touch/issues/1033

**Comment by james-lyon** [comment]
Having reinstalled everything, this is now working and can remain closed.
